### ISSUE TITLE
Please bump version number and do a PyPi release

### ISSUE THREAD

**Issue by shellster** [starnavi-team/django-partitioning#6]
You merged my PR (thank you), but this is bug fix and functionality change.  I would appreciate it if you could bump the version number and then do a release to PyPi so that they are in sync and the bug fix is accessible to most users.

**Comment by shellster** [comment]
Apologies for the new issue, but I wasn't sure you would get notified on the old issue since it was already closed.

**Comment by ndv88** [comment]
Hello! Thanks for your contribution. I’ve merged your merge request, and I’ll be preparing a new release today.

**Comment by ndv88** [comment]
Issue solved

**Comment by shellster** [comment]
Can you please push this to PyPi: https://pypi.org/project/django-postgresql-partitioning/
